version: 2.1

anchors:
  hello: &hello
    - run:
        name: Hello
        command: |
          FOO="World"

commands:
  hello:
    steps:
      - run:
          name: Say Hello
          command: |
            echo "export BAR=Hello" >> $BASH_ENV

orbs:
  android: circleci/android@0.2.1

parameters:
  build_variant:
    type: enum
    enum: ["debug", "release"]
    default: "debug"
  pull_request_title:
    type: string
    default: ""


jobs:
  deploy:
    executor: android/android
    steps:
      - checkout
      - hello
      - run:
          name: Test
          command: |
            echo << pipeline.parameters.build_variant>>
            echo << pipeline.parameters.pull_request_title >>
            echo "Branch $branch"
            echo $ENV
            ENV_UPPER_CASE=${ENV[@]~}
            echo $ENV_UPPER_CASE
      - run:
          name: Build with Gradle
          command: echo "build"
      - run:
          name: Echo
          command: echo "echo"
  lint:
    executor: android/android
    steps:
      - checkout
      - hello

workflows:
  version: 2.1
  build_deploy:
    when:
      - equal: [debug, << pipeline.parameters.build_variant >>]
    jobs:
      - deploy:
          name: deploy
  release:
    when:
      - equal: [release, << pipeline.parameters.build_variant >>]
    jobs:
      - deploy:
          name: release


