version: 2

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew build

  test:
    steps:
      - run:
          command: echo "test"
          
workflows:
  version: 2
  build:
    jobs:
      - test
      - build:
          filters:
            branches:
              only: master
