version: 2.1

anchors:
  hello: &hello
    - run: echo "Hello"

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    parameters:
      env:
        type: enum
        enum: ["dev", "stg", "production"]

    steps:
      - checkout
      - run:
          name: Test
          command: |
            ENV=($<< parameters.env >>)
            echo $ENV
            ENV_UPPER_CASE=${ENV[@]~}
            echo $ENV_UPPER_CASE
      - run: ./gradlew build
      - <<: *hello

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          name: deploy_dev
          env: dev

