version: 2.1

anchors:
  hello: &hello
    - run:
        name: Hello
        command: |
          FOO="World"

commands:
  hello:
    steps:
      - run:
          name: Say Hello
          commands: |
            ENV="Hello"

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    parameters:
      env:
        type: enum
        enum: ["debug", "release"]

    steps:
      - checkout
      - hello
      - <<: *hello
      - run:
          name: Test
          command: |
            echo $ENV
            echo $FOO
            ENV=(<< parameters.env >>)
            echo $ENV
            ENV_UPPER_CASE=${ENV[@]~}
            echo $ENV_UPPER_CASE
      - run:
          name: Build with Gradle
          command: ./gradlew assemble<< parameter.env >>
      - run:
          name: Echo
          command: ls app/build/outputs/apk/debug

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          name: deploy_dev
          env: debug

