version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run:
          command: ./gradlew build
          
workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            only: master
