version: 2

orbs:
  android: circleci/android@0.2.1

anchors:
  hello: &hello
    - run: echo "Hello"

jobs:
  build:
    executor: android/android

    steps:
      - checkout
      - run: ./gradlew build
      - <<: *hello

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
