version: 2.1

parameters:
  run_deploy:
    type: boolean
    default: false

anchors:
  hello: &hello
    - run:
        name: Hello
        command: |
          FOO="World"

commands:
  hello:
    steps:
      - run:
          name: Say Hello
          command: |
            echo "export BAR=Hello" >> $BASH_ENV

orbs:
  android: circleci/android@0.2.1

jobs:
  deploy:
    executor: android/android
    parameters:
      env:
        type: enum
        enum: ["debug", "release"]
    steps:
      - checkout
      - hello
      - <<: *hello
      - run:
          name: Test
          command: |
            echo $BAR
            echo $FOO
            ENV=(<< parameters.env >>)
            echo $ENV
            ENV_UPPER_CASE=${ENV[@]~}
            echo $ENV_UPPER_CASE
      - run:
          name: Build with Gradle
          command: ./gradlew assemble<< parameters.env >>
      - run:
          name: Echo
          command: ls app/build/outputs/apk/debug

workflows:
  version: 2.1
  build_deploy:
    when: << pipeline.parameters.run_deploy >>
    jobs:
      - deploy:
          name: deploy_dev
          env: debug

